Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: The Amazon Machine Image (AMI) ID for the EC2 instance.

  EnvType:
    Type: String
    Default: test
    AllowedValues:
      - prod
      - test
    Description: Must specify prod or test

Conditions:
  CreateProdResources: !Equals
    - !Ref EnvType
    - prod
  CreateTestResources: !Equals
    - !Ref EnvType
    - test

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Condition: CreateProdResources
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.small

  EC2Intancetest:
    Type: AWS::EC2::Instance
    Condition: CreateTestResources
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.micro

  NewVolume:
    Type: AWS::EC2::Volume
    Condition: CreateProdResources
    Properties:
      Size: 1
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone

  MoutPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: CreateProdResources
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref NewVolume
      Device: /dev/sdh

Outputs:
  VolumeId:
    Condition: CreateProdResources
    Value: !Ref NewVolume
    Description: ID do novo volume criado em ambiente de produção