Parameters:
  EnvironmentName:
    Description: Environment Name
    Type: String
    AllowedValues:
      - development
      - production
    ConstraintDescription: must be development or production

Mappings:
  AWSRegionArch2AMI:
    af-sout-1:
      HVM64: ami-06db08e8636583118
    us-east-1:
      HVM64: ami-0742b4e673072066f
    us-east-2:
      HVM64: ami-05d72852800cbf29e
    us-west-1:
      HVM64: ami-0577b787189839998
    us-west-2:
      HVM64: ami-0518bb0e75d3619ca
  EnvironmentToInstanceType:
    development:
      instanceType: t2.micro
    production:
      instanceType: t2.small

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap
        - EnvironmentToInstanceType
        - !Ref EnvironmentName
        - instanceType
      ImageId: !FindInMap
        - AWSRegionArch2AMI
        - !Ref AWS::Region
        - HVM64