Parameters:
  InstanceType:
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Conditions:
  IsProd: !Equals
    - !Ref Environment
    - prod
  IsDev: !Equals
    - !Ref Environment
    - dev
  IsProdInstanceType: !Equals
    - !Ref InstanceType
    - t2.medium
  IsDevInstanceType: !Or
    - !Equals
      - !Ref InstanceType
      - t2.micro
    - !Equals
      - !Ref InstanceType
      - t2.small

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Condition: IsProd
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId